// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Munilytics.Server.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Munilytics.Server.Migrations
{
    [DbContext(typeof(MunilyticsDbContext))]
    partial class MunilyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.DimGender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Dim_Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "T",
                            GenderName = "Total",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "F",
                            GenderName = "Female",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "M",
                            GenderName = "Male",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.DimKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auspice")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDividedByGender")
                        .HasColumnType("boolean");

                    b.Property<string>("KpiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MunicipalityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Perspective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dim_KPIs");
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.DimMunicipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkrGroupCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkrGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dim_Municipalities");
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.DimTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Decade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsElectionYear")
                        .HasColumnType("boolean");

                    b.Property<string>("MandatePeriod")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("RelativeYear")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Dim_Time");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Decade = 1990,
                            IsElectionYear = true,
                            MandatePeriod = "1994-1997",
                            RelativeYear = -32,
                            Year = 1994
                        },
                        new
                        {
                            Id = 2,
                            Decade = 1990,
                            IsElectionYear = false,
                            MandatePeriod = "1994-1997",
                            RelativeYear = -31,
                            Year = 1995
                        },
                        new
                        {
                            Id = 3,
                            Decade = 1990,
                            IsElectionYear = false,
                            MandatePeriod = "1994-1997",
                            RelativeYear = -30,
                            Year = 1996
                        },
                        new
                        {
                            Id = 4,
                            Decade = 1990,
                            IsElectionYear = false,
                            MandatePeriod = "1994-1997",
                            RelativeYear = -29,
                            Year = 1997
                        },
                        new
                        {
                            Id = 5,
                            Decade = 1990,
                            IsElectionYear = true,
                            MandatePeriod = "1998-2001",
                            RelativeYear = -28,
                            Year = 1998
                        },
                        new
                        {
                            Id = 6,
                            Decade = 1990,
                            IsElectionYear = false,
                            MandatePeriod = "1998-2001",
                            RelativeYear = -27,
                            Year = 1999
                        },
                        new
                        {
                            Id = 7,
                            Decade = 2000,
                            IsElectionYear = false,
                            MandatePeriod = "1998-2001",
                            RelativeYear = -26,
                            Year = 2000
                        },
                        new
                        {
                            Id = 8,
                            Decade = 2000,
                            IsElectionYear = false,
                            MandatePeriod = "1998-2001",
                            RelativeYear = -25,
                            Year = 2001
                        },
                        new
                        {
                            Id = 9,
                            Decade = 2000,
                            IsElectionYear = true,
                            MandatePeriod = "2002-2005",
                            RelativeYear = -24,
                            Year = 2002
                        },
                        new
                        {
                            Id = 10,
                            Decade = 2000,
                            IsElectionYear = false,
                            MandatePeriod = "2002-2005",
                            RelativeYear = -23,
                            Year = 2003
                        },
                        new
                        {
                            Id = 11,
                            Decade = 2000,
                            IsElectionYear = false,
                            MandatePeriod = "2002-2005",
                            RelativeYear = -22,
                            Year = 2004
                        },
                        new
                        {
                            Id = 12,
                            Decade = 2000,
                            IsElectionYear = false,
                            MandatePeriod = "2002-2005",
                            RelativeYear = -21,
                            Year = 2005
                        },
                        new
                        {
                            Id = 13,
                            Decade = 2000,
                            IsElectionYear = true,
                            MandatePeriod = "2006-2009",
                            RelativeYear = -20,
                            Year = 2006
                        },
                        new
                        {
                            Id = 14,
                            Decade = 2000,
                            IsElectionYear = false,
                            MandatePeriod = "2006-2009",
                            RelativeYear = -19,
                            Year = 2007
                        },
                        new
                        {
                            Id = 15,
                            Decade = 2000,
                            IsElectionYear = false,
                            MandatePeriod = "2006-2009",
                            RelativeYear = -18,
                            Year = 2008
                        },
                        new
                        {
                            Id = 16,
                            Decade = 2000,
                            IsElectionYear = false,
                            MandatePeriod = "2006-2009",
                            RelativeYear = -17,
                            Year = 2009
                        },
                        new
                        {
                            Id = 17,
                            Decade = 2010,
                            IsElectionYear = true,
                            MandatePeriod = "2010-2013",
                            RelativeYear = -16,
                            Year = 2010
                        },
                        new
                        {
                            Id = 18,
                            Decade = 2010,
                            IsElectionYear = false,
                            MandatePeriod = "2010-2013",
                            RelativeYear = -15,
                            Year = 2011
                        },
                        new
                        {
                            Id = 19,
                            Decade = 2010,
                            IsElectionYear = false,
                            MandatePeriod = "2010-2013",
                            RelativeYear = -14,
                            Year = 2012
                        },
                        new
                        {
                            Id = 20,
                            Decade = 2010,
                            IsElectionYear = false,
                            MandatePeriod = "2010-2013",
                            RelativeYear = -13,
                            Year = 2013
                        },
                        new
                        {
                            Id = 21,
                            Decade = 2010,
                            IsElectionYear = true,
                            MandatePeriod = "2014-2017",
                            RelativeYear = -12,
                            Year = 2014
                        },
                        new
                        {
                            Id = 22,
                            Decade = 2010,
                            IsElectionYear = false,
                            MandatePeriod = "2014-2017",
                            RelativeYear = -11,
                            Year = 2015
                        },
                        new
                        {
                            Id = 23,
                            Decade = 2010,
                            IsElectionYear = false,
                            MandatePeriod = "2014-2017",
                            RelativeYear = -10,
                            Year = 2016
                        },
                        new
                        {
                            Id = 24,
                            Decade = 2010,
                            IsElectionYear = false,
                            MandatePeriod = "2014-2017",
                            RelativeYear = -9,
                            Year = 2017
                        },
                        new
                        {
                            Id = 25,
                            Decade = 2010,
                            IsElectionYear = true,
                            MandatePeriod = "2018-2021",
                            RelativeYear = -8,
                            Year = 2018
                        },
                        new
                        {
                            Id = 26,
                            Decade = 2010,
                            IsElectionYear = false,
                            MandatePeriod = "2018-2021",
                            RelativeYear = -7,
                            Year = 2019
                        },
                        new
                        {
                            Id = 27,
                            Decade = 2020,
                            IsElectionYear = false,
                            MandatePeriod = "2018-2021",
                            RelativeYear = -6,
                            Year = 2020
                        },
                        new
                        {
                            Id = 28,
                            Decade = 2020,
                            IsElectionYear = false,
                            MandatePeriod = "2018-2021",
                            RelativeYear = -5,
                            Year = 2021
                        },
                        new
                        {
                            Id = 29,
                            Decade = 2020,
                            IsElectionYear = true,
                            MandatePeriod = "2022-2025",
                            RelativeYear = -4,
                            Year = 2022
                        },
                        new
                        {
                            Id = 30,
                            Decade = 2020,
                            IsElectionYear = false,
                            MandatePeriod = "2022-2025",
                            RelativeYear = -3,
                            Year = 2023
                        },
                        new
                        {
                            Id = 31,
                            Decade = 2020,
                            IsElectionYear = false,
                            MandatePeriod = "2022-2025",
                            RelativeYear = -2,
                            Year = 2024
                        },
                        new
                        {
                            Id = 32,
                            Decade = 2020,
                            IsElectionYear = false,
                            MandatePeriod = "2022-2025",
                            RelativeYear = -1,
                            Year = 2025
                        },
                        new
                        {
                            Id = 33,
                            Decade = 2020,
                            IsElectionYear = true,
                            MandatePeriod = "2026-2029",
                            RelativeYear = 0,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.FactKpiMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("DimGenderId")
                        .HasColumnType("integer");

                    b.Property<int>("DimKpiId")
                        .HasColumnType("integer");

                    b.Property<int>("DimMunicipalityId")
                        .HasColumnType("integer");

                    b.Property<int>("DimTimeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefinite")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LatestUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DimGenderId");

                    b.HasIndex("DimKpiId");

                    b.HasIndex("DimMunicipalityId");

                    b.HasIndex("DimTimeId");

                    b.ToTable("Fact_KpiMeasurements");
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSync")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Munilytics.Server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Munilytics.Server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Munilytics.Server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Munilytics.Server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.FactKpiMeasurement", b =>
                {
                    b.HasOne("Munilytics.Server.Domain.Entities.DimGender", "DimGender")
                        .WithMany("FactKpiMeasurements")
                        .HasForeignKey("DimGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Munilytics.Server.Domain.Entities.DimKpi", "DimKpi")
                        .WithMany("FactKpiMeasurements")
                        .HasForeignKey("DimKpiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Munilytics.Server.Domain.Entities.DimMunicipality", "DimMunicipality")
                        .WithMany("FactKpiMeasurements")
                        .HasForeignKey("DimMunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Munilytics.Server.Domain.Entities.DimTime", "DimTime")
                        .WithMany("FactKpiMeasurements")
                        .HasForeignKey("DimTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimGender");

                    b.Navigation("DimKpi");

                    b.Navigation("DimMunicipality");

                    b.Navigation("DimTime");
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.DimGender", b =>
                {
                    b.Navigation("FactKpiMeasurements");
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.DimKpi", b =>
                {
                    b.Navigation("FactKpiMeasurements");
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.DimMunicipality", b =>
                {
                    b.Navigation("FactKpiMeasurements");
                });

            modelBuilder.Entity("Munilytics.Server.Domain.Entities.DimTime", b =>
                {
                    b.Navigation("FactKpiMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
